"use client";

import { SlidersHorizontal } from "lucide-react";
import type { Platform, SortKey } from "@/types/product";

type Props = { sortKey: SortKey; onSortChange: (v: SortKey) => void; selectedPlatform: Platform | "全部"; onPlatformChange: (v: Platform | "全部") => void; platforms: Platform[]; minPrice: string; maxPrice: string; onMinPriceChange: (v: string) => void; onMaxPriceChange: (v: string) => void; returnOnly: boolean; onReturnOnlyChange: (v: boolean) => void; resultCount: number };

export function FilterBar(props: Props) {
  return <section className="rounded-[24px] border border-line bg-white p-4 shadow-card"><div className="mb-4 flex items-center gap-2"><SlidersHorizontal className="h-5 w-5 text-indigo-600" /><div><h2 className="text-lg font-semibold text-ink">排序与筛选</h2><p className="text-xs text-muted">当前显示 {props.resultCount} 个匹配商品</p></div></div><div className="grid gap-3 lg:grid-cols-[1.2fr_1fr_1fr_auto]"><label><span className="mb-2 block text-xs font-semibold text-muted">排序方式</span><select className="focus-ring h-11 w-full rounded-2xl border border-line px-3 text-sm" value={props.sortKey} onChange={(e) => props.onSortChange(e.target.value as SortKey)}><option value="recommendation">综合推荐分最高</option><option value="price">价格从低到高</option><option value="similarity">相似度从高到低</option><option value="rating">评分从高到低</option><option value="sales">销量从高到低</option></select></label><label><span className="mb-2 block text-xs font-semibold text-muted">平台</span><select className="focus-ring h-11 w-full rounded-2xl border border-line px-3 text-sm" value={props.selectedPlatform} onChange={(e) => props.onPlatformChange(e.target.value as Platform | "全部")}><option value="全部">全部平台</option>{props.platforms.map((p) => <option key={p} value={p}>{p}</option>)}</select></label><div><span className="mb-2 block text-xs font-semibold text-muted">价格区间</span><div className="grid grid-cols-2 gap-2"><input className="focus-ring h-11 min-w-0 rounded-2xl border border-line px-3 text-sm" placeholder="最低" value={props.minPrice} onChange={(e) => props.onMinPriceChange(e.target.value)} /><input className="focus-ring h-11 min-w-0 rounded-2xl border border-line px-3 text-sm" placeholder="最高" value={props.maxPrice} onChange={(e) => props.onMaxPriceChange(e.target.value)} /></div></div><label className="flex items-end"><span className="flex h-11 cursor-pointer items-center gap-2 rounded-2xl border border-line px-4 text-sm font-semibold"><input type="checkbox" checked={props.returnOnly} onChange={(e) => props.onReturnOnlyChange(e.target.checked)} />只看支持退货</span></label></div></section>;
}
