import { ArrowUpRight, BadgeCheck, MessageSquareText, RotateCcw, Star, Truck } from "lucide-react";
import type { ScoredProduct } from "@/types/product";

export function ProductCard({ product }: { product: ScoredProduct }) {
  return <article className="overflow-hidden rounded-[24px] border border-line bg-white shadow-card"><div className="grid lg:grid-cols-[220px_1fr]"><div className="bg-surface p-4"><img src={product.image} alt={product.title} className="h-56 w-full rounded-2xl bg-white object-cover" /></div><div className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="mb-2 flex gap-2"><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">{product.platform}</span><span className="rounded-full bg-surface px-3 py-1 text-xs font-semibold text-muted">相似度 {product.similarityScore}</span></div><h3 className="text-lg font-semibold leading-7 text-ink">{product.title}</h3><p className="mt-2 text-sm text-muted">{product.shopName}</p></div><div className="text-right"><p className="text-3xl font-bold text-rose-600">¥{product.price}</p><p className="text-sm text-muted line-through">¥{product.originalPrice}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Star className="h-4 w-4" />} label="评分" value={`${product.rating} / 5`} /><Metric label="销量" value={`${product.sales.toLocaleString()}+`} /><Metric label="评论" value={`${product.reviewCount.toLocaleString()} 条`} /><Metric icon={<BadgeCheck className="h-4 w-4" />} label="推荐分" value={`${product.recommendationScore}`} strong /></div><div className="mt-5 grid gap-3 md:grid-cols-2"><Info icon={<Truck className="h-4 w-4" />} text={product.shipping} /><Info icon={<RotateCcw className="h-4 w-4" />} text={product.returnPolicy} /></div><div className="mt-5 rounded-2xl bg-surface p-4"><div className="mb-3 flex items-center gap-2 text-sm font-semibold text-ink"><MessageSquareText className="h-4 w-4 text-indigo-600" />AI 评论总结</div><div className="grid gap-3 text-sm leading-6 text-muted md:grid-cols-3"><p><b className="text-ink">好评集中点：</b>{product.reviewSummary.positives}</p><p><b className="text-ink">差评集中点：</b>{product.reviewSummary.negatives}</p><p><b className="text-ink">购买建议：</b>{product.reviewSummary.advice}</p></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-4"><div className="flex flex-wrap gap-2">{product.positiveTags.map((tag) => <span key={tag} className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">+ {tag}</span>)}{product.negativeTags.map((tag) => <span key={tag} className="rounded-full bg-rose-50 px-3 py-1 text-xs font-semibold text-rose-700">- {tag}</span>)}</div><a href={product.productUrl} className="focus-ring inline-flex items-center gap-2 rounded-2xl bg-ink px-5 py-3 text-sm font-semibold text-white">查看商品<ArrowUpRight className="h-4 w-4" /></a></div></div></div></article>;
}

function Metric({ icon, label, value, strong }: { icon?: React.ReactNode; label: string; value: string; strong?: boolean }) {
  return <div className="rounded-2xl border border-line bg-white p-3"><p className="flex items-center gap-1 text-xs font-semibold text-muted">{icon}{label}</p><p className={`mt-1 font-semibold ${strong ? "text-indigo-700" : "text-ink"}`}>{value}</p></div>;
}

function Info({ icon, text }: { icon: React.ReactNode; text: string }) {
  return <p className="flex items-center gap-2 rounded-2xl border border-line px-3 py-2 text-sm text-muted"><span className="text-indigo-600">{icon}</span>{text}</p>;
}
